// Package image builds a workspace image with its dependencies baked in.
//
// This exists because a container is the wrong place to install things. Running
// `rosdep install` inside a live container works, and then the first `ros2pi up
// --recreate` -- or a ros2pi upgrade, or a config edit -- throws it away and the
// next build fails with a missing module the user knows they installed.
//
// So dependencies go in an image instead: declared in package.xml, resolved by
// rosdep at build time, and surviving recreate, reboot and upgrade. The same
// image rebuilds identically on another Pi, which a hand-installed container
// never will.
package image

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/artineering/ros2pi/internal/config"
	"github.com/artineering/ros2pi/internal/errs"
)

// ManifestDir is where the staged package.xml files live inside the build
// context.
const ManifestDir = "manifests"

// dockerfileTemplate is generated fresh on every build rather than kept in the
// workspace, so there is never a question of whether the file is ours or the
// user's. To customise, write your own Dockerfile and point ros.image at it --
// that already works and needs nothing from us.
const dockerfileTemplate = `# Generated by ros2pi. Do not edit: this file is rebuilt on every
# ` + "`ros2pi image build`" + `.
#
# To customise, build your own image however you like and set ros.image in
# ros2pi.toml to point at it. ros2pi does not care where an image came from.
ARG BASE=%s
FROM ${BASE}

# rosdep resolves package.xml dependencies to apt packages, and needs a package
# list to resolve against: the ROS images ship with /var/lib/apt/lists emptied.
#
# Running rosdep update as root warns. That is expected and correct here: in an
# image build there is no other user to be.
RUN apt-get update \
 && rosdep update --rosdistro "$ROS_DISTRO"

# Only the package.xml files are copied, not the source. This layer is what
# caches: editing your nodes does not reinstall your dependencies, and changing
# a dependency does.
COPY %s/ /tmp/ros2pi-manifests/

RUN rosdep install \
      --from-paths /tmp/ros2pi-manifests \
      --ignore-src \
      --rosdistro "$ROS_DISTRO" \
      -y \
 && rm -rf /tmp/ros2pi-manifests /var/lib/apt/lists/*
`

// Dockerfile returns the Dockerfile ros2pi would build for this workspace.
func Dockerfile(cfg config.Config) string {
	return fmt.Sprintf(dockerfileTemplate, baseImage(cfg), ManifestDir)
}

// baseImage is what the workspace image is built FROM.
//
// It is separate from ros.image because ros.image becomes the BUILT image after
// a build; using it as the base too would make the next build stack on top of
// itself, growing without bound.
func baseImage(cfg config.Config) string {
	if cfg.Image.Base != "" {
		return cfg.Image.Base
	}
	return "ros:" + cfg.ROS.Distro
}

// Name is the tag for a workspace's image.
//
// It carries the same hash as the container name so that two workspaces with
// the same basename cannot collide, and so an image is traceable to the
// workspace that produced it.
func Name(cfg config.Config, containerName string) string {
	if cfg.Image.Name != "" {
		return cfg.Image.Name
	}
	return containerName + ":latest"
}

// FindManifests returns every package.xml under the workspace's src/, sorted.
func FindManifests(root string) ([]string, error) {
	src := filepath.Join(root, "src")
	var out []string

	err := filepath.WalkDir(src, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			// Build output can contain copies of package.xml; they are not
			// sources and would confuse rosdep.
			switch d.Name() {
			case "build", "install", "log", ".git":
				return fs.SkipDir
			}
			return nil
		}
		if d.Name() == "package.xml" {
			out = append(out, p)
		}
		return nil
	})
	if err != nil {
		if os.IsNotExist(err) {
			return nil, errs.New(errs.CodeNoWorkspace, "this workspace has no src/ directory").
				WithDetail("looked in %s", src).
				WithFix(&errs.Fix{Steps: []errs.Step{
					{Text: "create a package first:",
						Cmd: "ros2pi pkg create --build-type ament_python --node-name my_node my_pkg"},
				}})
		}
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}

// StageContext writes a minimal docker build context into dir: the generated
// Dockerfile plus every package.xml, at its path relative to src/.
//
// The context deliberately excludes the source. A workspace can be large, and
// including it would both slow every build and invalidate the dependency layer
// on every code edit -- which is exactly the caching behaviour that makes this
// worth doing at all.
func StageContext(cfg config.Config, manifests []string, dir string) error {
	if err := os.WriteFile(filepath.Join(dir, "Dockerfile"),
		[]byte(Dockerfile(cfg)), 0o644); err != nil {
		return fmt.Errorf("write Dockerfile: %w", err)
	}

	src := filepath.Join(cfg.Root, "src")
	for _, m := range manifests {
		rel, err := filepath.Rel(src, m)
		if err != nil {
			return err
		}
		dst := filepath.Join(dir, ManifestDir, rel)
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		body, err := os.ReadFile(m)
		if err != nil {
			return err
		}
		if err := os.WriteFile(dst, body, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// BuildArgs is the docker command line for building the workspace image.
func BuildArgs(cfg config.Config, tag, contextDir string, noCache bool) []string {
	args := []string{"build", "--build-arg", "BASE=" + baseImage(cfg), "-t", tag}
	if noCache {
		args = append(args, "--no-cache")
	}
	return append(args, contextDir)
}

// PackageNames lists the packages a set of manifests declares, for reporting.
// A crude scan is enough: this is a progress message, not a parser.
func PackageNames(manifests []string) []string {
	var out []string
	for _, m := range manifests {
		body, err := os.ReadFile(m)
		if err != nil {
			continue
		}
		if n := between(string(body), "<name>", "</name>"); n != "" {
			out = append(out, strings.TrimSpace(n))
		}
	}
	sort.Strings(out)
	return out
}

func between(s, a, b string) string {
	i := strings.Index(s, a)
	if i < 0 {
		return ""
	}
	j := strings.Index(s[i+len(a):], b)
	if j < 0 {
		return ""
	}
	return s[i+len(a) : i+len(a)+j]
}
