package hostfacts

import "testing"

var pi4Model = PiModel{Raw: "Raspberry Pi 4 Model B Rev 1.5", Family: FamilyPi4}
var pi5Model = PiModel{Raw: "Raspberry Pi 5 Model B Rev 1.0", Family: FamilyPi5}
var cm4Model = PiModel{Raw: "Raspberry Pi Compute Module 4 Rev 1.1", Family: FamilyPi4}

// config.txt conditional filter sections are the common case, not a corner
// case: stock Raspberry Pi OS ships [cm4], [cm5], [pi5] and [all] out of the
// box. A parser that ignores them attributes other hardware's settings to this
// host, which is precisely the confidently-wrong diagnosis `check` exists to
// prevent.
func TestParseBootConfig_FilterSections(t *testing.T) {
	tests := []struct {
		name    string
		model   PiModel
		in      string
		wantI2C Tristate
		wantSPI Tristate
	}{
		{
			name:    "a [pi5] setting must not apply to a Pi 4",
			model:   pi4Model,
			in:      "[pi5]\ndtparam=i2c_arm=on\n[all]\n",
			wantI2C: Unset,
		},
		{
			name:    "the same [pi5] setting applies to a Pi 5",
			model:   pi5Model,
			in:      "[pi5]\ndtparam=i2c_arm=on\n[all]\n",
			wantI2C: On,
		},
		{
			name:    "[all] returns to unconditional after an excluded section",
			model:   pi4Model,
			in:      "[pi5]\ndtparam=i2c_arm=on\n[all]\ndtparam=spi=on\n",
			wantI2C: Unset,
			wantSPI: On,
		},
		{
			name:    "settings before any filter are unconditional",
			model:   pi4Model,
			in:      "dtparam=i2c_arm=on\n[pi5]\ndtparam=spi=on\n",
			wantI2C: On,
			wantSPI: Unset,
		},
		{
			name:    "[none] disables a block entirely",
			model:   pi4Model,
			in:      "[none]\ndtparam=i2c_arm=on\n",
			wantI2C: Unset,
		},
		{
			name:    "[pi4] matches a Pi 4",
			model:   pi4Model,
			in:      "[pi4]\ndtparam=i2c_arm=on\n",
			wantI2C: On,
		},
		{
			name:  "[cm4] does not match a plain Pi 4 board",
			model: pi4Model,
			// [cm4] selects Compute Modules; a Pi 4 B is BCM2711 but not a CM.
			in:      "[cm4]\ndtparam=i2c_arm=on\n",
			wantI2C: Unset,
		},
		{
			name:    "a commented dtparam inside a matching section stays unset",
			model:   pi4Model,
			in:      "[all]\n#dtparam=i2c_arm=on\n",
			wantI2C: Unset,
		},
		{
			name:    "an explicit off is Off, not Unset",
			model:   pi4Model,
			in:      "[all]\ndtparam=i2c_arm=off\n",
			wantI2C: Off,
		},
		{
			name:    "multiple params on one dtparam line",
			model:   pi4Model,
			in:      "dtparam=i2c_arm=on,spi=on\n",
			wantI2C: On,
			wantSPI: On,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			b := Boot{I2CArm: Unset, SPI: Unset, EnableUART: Unset}
			parseBootConfig(tc.in, tc.model, &b)
			if b.I2CArm != tc.wantI2C {
				t.Errorf("i2c_arm = %q, want %q", b.I2CArm, tc.wantI2C)
			}
			if tc.wantSPI != "" && b.SPI != tc.wantSPI {
				t.Errorf("spi = %q, want %q", b.SPI, tc.wantSPI)
			}
		})
	}
}

// A section we cannot evaluate must not have its settings applied, and must say
// so, rather than silently guessing in either direction.
func TestParseBootConfig_UnevaluatableFilterWarns(t *testing.T) {
	b := Boot{I2CArm: Unset}
	warns := parseBootConfig("[EDID=VSC-TD2220]\ndtparam=i2c_arm=on\n", pi4Model, &b)

	if b.I2CArm != Unset {
		t.Errorf("i2c_arm = %q, want unset: an [EDID=...] section cannot be evaluated", b.I2CArm)
	}
	if len(warns) != 1 || warns[0].Code != "boot.config.filter.unevaluated" {
		t.Fatalf("warnings = %+v, want one boot.config.filter.unevaluated", warns)
	}
}

// A Compute Module is the right board class but we do not pin the revision, so
// the verdict is "unknown" (warn, do not apply) rather than a false match.
func TestParseBootConfig_ComputeModuleIsUnevaluated(t *testing.T) {
	b := Boot{I2CArm: Unset}
	warns := parseBootConfig("[cm4]\ndtparam=i2c_arm=on\n", cm4Model, &b)
	if b.I2CArm != Unset {
		t.Errorf("i2c_arm = %q, want unset", b.I2CArm)
	}
	if len(warns) == 0 {
		t.Error("expected a warning that [cm4] could not be evaluated")
	}
}

// An unknown family cannot judge a model filter either way.
func TestParseBootConfig_UnknownFamilyCannotEvaluateModelFilter(t *testing.T) {
	b := Boot{I2CArm: Unset}
	warns := parseBootConfig("[pi4]\ndtparam=i2c_arm=on\n",
		PiModel{Family: FamilyUnknown}, &b)
	if b.I2CArm != Unset {
		t.Errorf("i2c_arm = %q, want unset when the family is unknown", b.I2CArm)
	}
	if len(warns) == 0 {
		t.Error("expected a warning")
	}
}

// The stub must be matched on its first line, not by scanning the whole file:
// a real config that merely mentions the phrase in a comment would otherwise be
// discarded, silently losing every setting the user wrote.
func TestIsStub(t *testing.T) {
	stub := "DO NOT EDIT THIS FILE\n\nThe file you are looking for has moved to /boot/firmware/config.txt"
	if !isStub(stub) {
		t.Error("real Pi OS stub not recognised")
	}
	realConfig := "# DO NOT EDIT THIS FILE - managed by Ansible\ndtparam=i2c_arm=on\n"
	if isStub(realConfig) {
		t.Error("a real config mentioning the phrase in a comment was treated as the stub")
	}
}
