package hostfacts

import (
	"bufio"
	"context"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

// containerGroupGIDs are the GIDs these names resolve to INSIDE the ROS image
// (Debian base-passwd allocates them statically). A host group is safe to pass
// by name only if the host's GID matches the value here -- which is checked,
// not assumed. Groups absent from this map never exist in the image and must
// always be passed numerically.
var containerGroupGIDs = map[string]int{"dialout": 20, "video": 44}

// probedGroups are the groups ros2pi may need to map into a container.
// probedGroups are the groups ros2pi may need to map into a container, plus
// "docker", whose membership gates whether the tool can run at all.
var probedGroups = []string{"docker", "gpio", "i2c", "spi", "dialout", "video", "render", "input"}

// bootConfigCandidates is ordered most-authoritative first. /boot/config.txt is
// a stub on modern Pi OS ("DO NOT EDIT THIS FILE / ... has moved to
// /boot/firmware/config.txt"), so it must never win.
var bootConfigCandidates = []string{"boot/firmware/config.txt", "boot/config.txt"}

// LinuxProber builds HostFacts from a HostIO.
//
// Version is a field rather than part of HostIO: the ros2pi version is not a
// property of the host, and putting it in the seam only widened it.
type LinuxProber struct {
	IO      HostIO
	Version string
}

func NewLinuxProber(io HostIO, version string) Prober {
	return LinuxProber{IO: io, Version: version}
}

func (p LinuxProber) Probe(ctx context.Context) (HostFacts, error) {
	e := p.IO
	f := HostFacts{
		SchemaVersion: SchemaVersion,
		ProbedAt:      time.Now().UTC(),
		ProbedBy:      p.Version,
	}

	machine, release, err := e.Uname()
	if err != nil {
		return f, fmt.Errorf("uname: %w", err)
	}
	f.Kernel = parseKernel(release)
	f.Arch = Arch{Machine: machine, Go: e.GoArch(), Dpkg: p.dpkgArch(ctx)}
	f.OS = p.osRelease()
	f.Identity = p.identity(&f.Warnings)
	f.Groups = p.groups(f.Identity)

	chips, warns := probeGPIOChips(e)
	f.GPIOChips = chips
	f.Warnings = append(f.Warnings, warns...)
	f.Model = p.model(chips, &f.Warnings)

	if cands, ok := gpioMemCandidates(f.Model.Family); ok {
		f.GPIOMem = p.devNodes(cands)
	} else {
		f.Warnings = append(f.Warnings, Warning{
			Code: "gpio.mem.unknown",
			Detail: "unknown Pi family: cannot tell whether this host uses /dev/gpiomem " +
				"(Pi 4 and earlier) or /dev/gpiomem0..4 (Pi 5); GPIO memory not probed",
		})
	}

	f.I2CBuses = p.globNodes("dev", `^i2c-\d+$`)
	f.I2CHeader = p.i2cHeader(&f.Warnings)
	f.SPIDevs = p.globNodes("dev", `^spidev\d+\.\d+$`)
	f.Serial = p.devNodes([]string{"/dev/serial0", "/dev/serial1", "/dev/ttyAMA0", "/dev/ttyS0"})
	f.USBSerial = p.globNodes("dev", `^tty(USB|ACM)\d+$`)
	f.Boot = p.boot(f.Model, &f.Warnings)
	f.Docker = p.docker(ctx, f.Groups)

	return f, nil
}

// gpioMemCandidates differs by family: Pi 4 and earlier expose a single
// /dev/gpiomem; Pi 5's RP1 replaced it with /dev/gpiomem0../dev/gpiomem4.
//
// An unknown family returns nothing rather than defaulting to the Pi 4 layout.
// Guessing here would contradict markHeaderChip, which refuses to guess about
// the same unknown host, and would report "/dev/gpiomem absent" in a bug report
// when the truth is "we did not know what to look for".
func gpioMemCandidates(fam Family) ([]string, bool) {
	switch fam {
	case FamilyPi5:
		return []string{"/dev/gpiomem0", "/dev/gpiomem1", "/dev/gpiomem2", "/dev/gpiomem3", "/dev/gpiomem4"}, true
	case FamilyPi4, FamilyPi123:
		return []string{"/dev/gpiomem"}, true
	}
	return nil, false
}

// model derives the family from the GPIO chip label, not the model string. The
// model string is for humans and is not a reliable key for device layout.
func (p LinuxProber) model(chips []GPIOChip, warns *[]Warning) PiModel {
	m := PiModel{Family: FamilyUnknown}
	if raw, err := readTrimmed(p.IO, "proc/device-tree/model"); err == nil {
		m.Raw = strings.TrimRight(raw, "\x00")
	}
	for _, c := range chips {
		if fam, ok := familyForLabel(c.Label); ok {
			m.Family = fam
			return m
		}
	}
	*warns = append(*warns, Warning{
		Code:   "model.family.unknown",
		Detail: fmt.Sprintf("could not derive Pi family from GPIO labels (model=%q)", m.Raw),
	})
	return m
}

// identity resolves the real user. Under sudo, geteuid() is 0, and using it
// would run the container as root and litter the workspace with root-owned
// files -- the precise bug this tool exists to prevent.
//
// SUDO_UID alone is enough to act on. Requiring SUDO_GID as well would mean a
// partial sudo environment silently falls back to root, reintroducing exactly
// that bug with UnderSudo=false, so nothing downstream could even notice. When
// SUDO_GID is missing or unparseable the GID is taken from the user's passwd
// entry, and a warning records it.
func (p LinuxProber) identity(warns *[]Warning) Identity {
	e := p.IO
	id := Identity{UID: e.Geteuid(), GID: e.Getegid()}

	uid, err := strconv.Atoi(e.Getenv("SUDO_UID"))
	if err != nil {
		if u, err := e.LookupUID(id.UID); err == nil {
			id.Username = u.Username
			// Prefer the passwd PRIMARY group over the effective gid.
			//
			// getegid() reflects transient group context: under `newgrp docker`
			// -- which ros2pi itself recommends for a stale session -- it is the
			// docker group, not the user's. Using it would write build output as
			// group=docker, and would change the container fingerprint the
			// moment the user logged back in normally, making a healthy
			// container look stale and demanding a pointless recreate.
			if gid, err := strconv.Atoi(u.Gid); err == nil {
				id.GID = gid
			}
		}
		return id
	}

	id.UID, id.UnderSudo = uid, true
	u, lookupErr := e.LookupUID(uid)
	if lookupErr == nil {
		id.Username = u.Username
	}

	if gid, err := strconv.Atoi(e.Getenv("SUDO_GID")); err == nil {
		id.GID = gid
		return id
	}

	// Fall back to the user's primary group rather than to root.
	if lookupErr == nil {
		if gid, err := strconv.Atoi(u.Gid); err == nil {
			id.GID = gid
			*warns = append(*warns, Warning{
				Code: "identity.sudo_gid.missing",
				Detail: fmt.Sprintf(
					"SUDO_UID=%d is set but SUDO_GID is not; using %s's primary group %d. "+
						"Running as root here would write root-owned files into the workspace.",
					uid, u.Username, gid),
			})
			return id
		}
	}

	*warns = append(*warns, Warning{
		Code: "identity.sudo_gid.unresolved",
		Detail: fmt.Sprintf(
			"SUDO_UID=%d is set but SUDO_GID is missing and uid %d has no resolvable "+
				"passwd entry; group ownership of workspace files may be wrong", uid, uid),
	})
	return id
}

// groups probes the host groups, returning them sorted by name so that argv
// built from them is deterministic.
func (p LinuxProber) groups(id Identity) []Group {
	out := make([]Group, 0, len(probedGroups))
	member := p.memberGIDs(id)
	session := p.sessionGIDs()
	for _, name := range probedGroups {
		g := Group{Name: name}
		if lg, err := p.IO.LookupGroup(name); err == nil {
			if gid, err := strconv.Atoi(lg.Gid); err == nil {
				g.GID, g.Exists = gid, true
				g.UserIsMember = member[gid]
				g.SessionHasGroup = session[gid]
				// NameResolvable is COMPUTED, never assumed from the name: it
				// holds only when the host GID matches the value the ROS image
				// will resolve that name to.
				if want, ok := containerGroupGIDs[name]; ok && gid == want {
					g.NameResolvable = true
				}
			}
		}
		out = append(out, g)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// sessionGIDs reports the groups THIS PROCESS actually carries. Under sudo the
// process credentials are root's, which say nothing about the invoking user's
// session, so the comparison is meaningless and is skipped.
func (p LinuxProber) sessionGIDs() map[int]bool {
	m := map[int]bool{}
	gids, err := p.IO.Getgroups()
	if err != nil {
		return m
	}
	for _, g := range gids {
		m[g] = true
	}
	return m
}

func (p LinuxProber) memberGIDs(id Identity) map[int]bool {
	m := map[int]bool{id.GID: true}
	u, err := p.IO.LookupUID(id.UID)
	if err != nil {
		return m
	}
	gids, err := p.IO.GroupIDs(u)
	if err != nil {
		return m
	}
	for _, s := range gids {
		if gid, err := strconv.Atoi(s); err == nil {
			m[gid] = true
		}
	}
	return m
}

func (p LinuxProber) devNodes(names []string) []DevNode {
	out := make([]DevNode, 0, len(names))
	for _, name := range names {
		out = append(out, p.devNode(name))
	}
	return out
}

// devNode stats a path and resolves symlinks. /dev/serial0 is a symlink, and
// docker --device on a symlink resolves it at create time to an
// inconsistently-named node inside the container, so callers need the real one.
//
// readlink(2) returns the raw target, which for /dev/serial0 is the RELATIVE
// "ttyS0". Handing that to --device would be nonsense, so it is rejoined
// against the link's directory to yield /dev/ttyS0.
func (p LinuxProber) devNode(name string) DevNode {
	n := DevNode{Path: name}
	if target, err := p.IO.Readlink(name); err == nil && target != name {
		if !path.IsAbs(target) {
			target = path.Join(path.Dir(name), target)
		}
		n.Resolved = target
	}
	st, err := p.IO.StatDev(name)
	if err != nil || !st.Exists {
		return n
	}
	n.Exists, n.Major, n.Minor = true, st.Major, st.Minor
	n.Mode, n.OwnerGID = st.Mode, st.OwnerGID
	return n
}

func (p LinuxProber) globNodes(dir, pattern string) []DevNode {
	re := regexp.MustCompile(pattern)
	entries, err := p.IO.ReadDir(dir)
	if err != nil {
		return nil
	}
	var names []string
	for _, e := range entries {
		if re.MatchString(e.Name()) {
			names = append(names, "/"+path.Join(dir, e.Name()))
		}
	}
	sort.Strings(names)
	return p.devNodes(names)
}

// stubFirstLine identifies the /boot/config.txt placeholder shipped since
// Bookworm, whose full text is:
//
//	DO NOT EDIT THIS FILE
//
//	The file you are looking for has moved to /boot/firmware/config.txt
//
// It is matched on the FIRST LINE only. Scanning the whole file for the phrase
// would misclassify a real config that merely mentions it in a comment (e.g.
// "# DO NOT EDIT THIS FILE - managed by Ansible"), silently discarding the
// user's actual settings.
const stubFirstLine = "DO NOT EDIT THIS FILE"

func isStub(data string) bool {
	line, _, _ := strings.Cut(data, "\n")
	return strings.TrimSpace(line) == stubFirstLine
}

// boot parses the firmware config, honouring conditional filter sections. A
// commented-out dtparam stays Unset rather than Off: "never mentioned" and
// "explicitly disabled" lead to different advice, and conflating them produces
// a confusing diagnosis.
func (p LinuxProber) boot(m PiModel, warns *[]Warning) Boot {
	b := Boot{I2CArm: Unset, SPI: Unset, EnableUART: Unset}

	if s, err := readTrimmed(p.IO, "boot/config.txt"); err == nil && isStub(s) {
		b.StubSeen = true
	}

	for _, cand := range bootConfigCandidates {
		data, err := readTrimmed(p.IO, cand)
		if err != nil {
			continue
		}
		if isStub(data) {
			continue // the placeholder; the real file is elsewhere
		}
		b.ConfigPath, b.Found = "/"+cand, true
		*warns = append(*warns, parseBootConfig(data, m, &b)...)
		return b
	}

	*warns = append(*warns, Warning{
		Code:   "boot.config.missing",
		Detail: "no readable firmware config.txt found; i2c/spi state is unknown",
	})
	return b
}

func (p LinuxProber) dpkgArch(ctx context.Context) string {
	r, err := p.IO.Exec(ctx, "dpkg", "--print-architecture")
	if err != nil || r.Code != 0 {
		return ""
	}
	return strings.TrimSpace(r.Stdout)
}

func (p LinuxProber) osRelease() OSRelease {
	var o OSRelease
	data, err := readTrimmed(p.IO, "etc/os-release")
	if err != nil {
		return o
	}
	sc := bufio.NewScanner(strings.NewReader(data))
	for sc.Scan() {
		k, v, ok := strings.Cut(sc.Text(), "=")
		if !ok {
			continue
		}
		v = strings.Trim(v, `"`)
		switch k {
		case "ID":
			o.ID = v
		case "VERSION_ID":
			o.VersionID = v
		case "PRETTY_NAME":
			o.Pretty = v
		}
	}
	return o
}

var kernelRE = regexp.MustCompile(`^(\d+)\.(\d+)\.(\d+)`)

func parseKernel(release string) Kernel {
	k := Kernel{Release: release}
	if m := kernelRE.FindStringSubmatch(release); m != nil {
		k.Major, _ = strconv.Atoi(m[1])
		k.Minor, _ = strconv.Atoi(m[2])
		k.Patch, _ = strconv.Atoi(m[3])
	}
	return k
}
