package hostfacts

import (
	"context"
	"testing"
)

// fakePi builds an Env describing a synthetic host. This is the whole point of
// the Env seam: a Pi 5 running kernel 6.6 can be tested on a Pi 4, on an x86
// laptop, or in CI, with no hardware anywhere.
type fakePi struct {
	files      map[string]string
	symlinks   map[string]string
	chips      map[string]GPIOChipInfoResult // /dev/gpiochipN -> info
	devs       map[string]DevStat
	groups     map[string]string
	env        map[string]string
	machine    string
	release    string
	dpkg       string
	chipIsSym  map[string]bool
	extraFiles map[string]string

	// docker simulation
	noDocker     bool            // docker absent from PATH
	dockerOut    string          // stdout of `docker info --format ...`
	dockerErr    string          // stderr when the daemon call fails
	dockerCode   int             // exit code of `docker info`
	sessionGroup map[string]bool // groups THIS session carries; nil => all of them
}

type errString string

func (e errString) Error() string { return string(e) }

const errNotFound = errString("not found")

func baseName(p string) string {
	for i := len(p) - 1; i >= 0; i-- {
		if p[i] == '/' {
			return p[i+1:]
		}
	}
	return p
}

// pi5 is a Raspberry Pi 5 on kernel 6.6.47+, where the header chip moved BACK
// to gpiochip0 from the 6.1-era gpiochip4. Identified purely by the rp1 label.
func pi5() fakePi {
	return fakePi{
		machine: "aarch64", release: "6.6.51-v8-16k+", dpkg: "arm64",
		files: map[string]string{
			"proc/device-tree/model": "Raspberry Pi 5 Model B Rev 1.0\x00",
			"etc/os-release":         "ID=debian\nVERSION_ID=\"13\"\nPRETTY_NAME=\"Debian GNU/Linux 13 (trixie)\"\n",
			"boot/config.txt":        "DO NOT EDIT THIS FILE\n\nThe file you are looking for has moved to /boot/firmware/config.txt\n",
			"boot/firmware/config.txt": "# Uncomment some or all of these\n" +
				"#dtparam=i2c_arm=on\ndtparam=spi=on\nenable_uart=1\n",
		},
		chips: map[string]GPIOChipInfoResult{
			"/dev/gpiochip0": {Name: "gpiochip0", Label: "pinctrl-rp1", Lines: 54},
		},
		devs: map[string]DevStat{
			"/dev/gpiomem0":  {Exists: true, IsChar: true, Major: 240, Minor: 0, Mode: 0o660, OwnerGID: 993},
			"/dev/spidev0.0": {Exists: true, IsChar: true, Major: 153, Minor: 0, Mode: 0o660, OwnerGID: 999},
			"/dev/ttyAMA10":  {Exists: true, IsChar: true, Major: 204, Minor: 74, Mode: 0o660, OwnerGID: 20},
			"/dev/serial0":   {Exists: true, IsChar: true, Major: 204, Minor: 74, Mode: 0o660, OwnerGID: 20},
		},
		symlinks: map[string]string{"/dev/serial0": "ttyAMA10"}, // relative, as readlink(2) returns
		groups:   map[string]string{"gpio": "993", "i2c": "994", "spi": "999", "dialout": "20", "video": "44"},
		env:      map[string]string{},
	}
}

func TestProbePi5_HeaderChipFoundByLabelNotNumber(t *testing.T) {
	f, err := NewLinuxProber(pi5().host(), "test").Probe(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if f.Model.Family != FamilyPi5 {
		t.Errorf("family = %q, want %q", f.Model.Family, FamilyPi5)
	}
	c, ok := f.HeaderChip()
	if !ok {
		t.Fatal("no header chip identified")
	}
	// The point: gpiochip0 on a Pi 5 is correct on kernel 6.6+, and it is the
	// LABEL that proves it, not the number.
	if c.Label != "pinctrl-rp1" || c.Name != "gpiochip0" {
		t.Errorf("header chip = %s[%s], want gpiochip0[pinctrl-rp1]", c.Name, c.Label)
	}
}

// A Pi 5 has /dev/gpiomem0..4, not the Pi 4's single /dev/gpiomem. Probing the
// wrong node yields a --device flag for a file that does not exist.
func TestProbePi5_UsesGpiomem0NotGpiomem(t *testing.T) {
	f, _ := NewLinuxProber(pi5().host(), "test").Probe(context.Background())
	var got []string
	for _, n := range f.GPIOMem {
		if n.Exists {
			got = append(got, n.Path)
		}
	}
	if len(got) != 1 || got[0] != "/dev/gpiomem0" {
		t.Errorf("gpiomem = %v, want [/dev/gpiomem0]", got)
	}
}

// readlink(2) returns a relative target; --device needs an absolute node.
func TestProbe_ResolvesRelativeSerialSymlinkToAbsolute(t *testing.T) {
	f, _ := NewLinuxProber(pi5().host(), "test").Probe(context.Background())
	for _, n := range f.Serial {
		if n.Path == "/dev/serial0" {
			if n.Resolved != "/dev/ttyAMA10" {
				t.Errorf("serial0 resolved = %q, want /dev/ttyAMA10", n.Resolved)
			}
			return
		}
	}
	t.Fatal("/dev/serial0 not probed")
}

// A commented-out dtparam is Unset, not Off, and the stub /boot/config.txt must
// never be mistaken for the real firmware config.
func TestProbe_BootConfigSkipsStubAndTreatsCommentedParamAsUnset(t *testing.T) {
	f, _ := NewLinuxProber(pi5().host(), "test").Probe(context.Background())
	if f.Boot.ConfigPath != "/boot/firmware/config.txt" {
		t.Errorf("config path = %q, want /boot/firmware/config.txt", f.Boot.ConfigPath)
	}
	if !f.Boot.StubSeen {
		t.Error("stub /boot/config.txt not detected")
	}
	if f.Boot.I2CArm != Unset {
		t.Errorf("i2c_arm = %q, want unset (it is commented out)", f.Boot.I2CArm)
	}
	if f.Boot.SPI != On {
		t.Errorf("spi = %q, want on", f.Boot.SPI)
	}
}

// The gpio/i2c/spi GIDs are dynamic and differ between hosts; nothing may
// hardcode this Pi 4's 986/988/989.
func TestProbe_DynamicGroupsAreNotStatic(t *testing.T) {
	f, _ := NewLinuxProber(pi5().host(), "test").Probe(context.Background())
	if g, _ := f.Group("gpio"); g.GID != 993 || g.NameResolvable {
		t.Errorf("gpio = %+v, want gid 993, name_resolvable=false", g)
	}
	if g, _ := f.Group("dialout"); g.GID != 20 || !g.NameResolvable {
		t.Errorf("dialout = %+v, want gid 20, name_resolvable=true", g)
	}
}

// Under sudo, geteuid() is 0. Using it would run the container as root and
// write root-owned files into the workspace.
func TestProbe_SudoResolvesToRealUser(t *testing.T) {
	p := pi5()
	p.env = map[string]string{"SUDO_UID": "1000", "SUDO_GID": "1000"}
	f, _ := NewLinuxProber(p.host(), "test").Probe(context.Background())
	if f.Identity.UID != 1000 || f.Identity.GID != 1000 || !f.Identity.UnderSudo {
		t.Errorf("identity = %+v, want uid/gid 1000 and UnderSudo", f.Identity)
	}
}

// An unrecognised chip label must warn and disable GPIO, never guess a layout.
func TestProbe_UnknownChipLabelWarnsRatherThanGuessing(t *testing.T) {
	p := pi5()
	p.chips = map[string]GPIOChipInfoResult{
		"/dev/gpiochip0": {Name: "gpiochip0", Label: "pinctrl-rp2-future", Lines: 54},
	}
	f, _ := NewLinuxProber(p.host(), "test").Probe(context.Background())
	if _, ok := f.HeaderChip(); ok {
		t.Error("guessed a header chip from an unknown label; must refuse")
	}
	if f.Model.Family != FamilyUnknown {
		t.Errorf("family = %q, want unknown", f.Model.Family)
	}
	if !hasWarning(f, "gpio.header.unknown") {
		t.Errorf("expected gpio.header.unknown warning, got %+v", f.Warnings)
	}
}

// Regression: Raspberry Pi OS ships /dev/gpiochip4 -> gpiochip0 on a Pi 4 as a
// compatibility shim for Pi 5 kernel-6.1-era code. It is the same device and an
// ioctl on it succeeds, so a naive enumerator reports a phantom third chip.
// Observed on real hardware; gpiodetect lists only the two real chips.
func TestProbe_SkipsGpiochipCompatSymlink(t *testing.T) {
	p := fakePi{
		machine: "aarch64", release: "6.18.34+rpt-rpi-v8", dpkg: "arm64",
		files: map[string]string{
			"proc/device-tree/model":   "Raspberry Pi 4 Model B Rev 1.5\x00",
			"boot/firmware/config.txt": "dtparam=i2c_arm=on\n",
		},
		chips: map[string]GPIOChipInfoResult{
			"/dev/gpiochip0": {Name: "gpiochip0", Label: "pinctrl-bcm2711", Lines: 58},
			"/dev/gpiochip1": {Name: "gpiochip1", Label: "raspberrypi-exp-gpio", Lines: 8},
			// The shim: same device, so the ioctl answers identically.
			"/dev/gpiochip4": {Name: "gpiochip0", Label: "pinctrl-bcm2711", Lines: 58},
		},
		chipIsSym: map[string]bool{"gpiochip4": true},
		groups:    map[string]string{"gpio": "986"},
		env:       map[string]string{},
	}
	f, err := NewLinuxProber(p.host(), "test").Probe(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(f.GPIOChips) != 2 {
		var names []string
		for _, c := range f.GPIOChips {
			names = append(names, c.Name)
		}
		t.Fatalf("got %d chips %v, want 2 (gpiochip4 is a symlink to gpiochip0)",
			len(f.GPIOChips), names)
	}
	if c, ok := f.HeaderChip(); !ok || c.Name != "gpiochip0" {
		t.Errorf("header chip = %v, want gpiochip0", c)
	}
}

func hasWarning(f HostFacts, code string) bool {
	for _, w := range f.Warnings {
		if w.Code == code {
			return true
		}
	}
	return false
}

func TestParseKernel(t *testing.T) {
	for _, tc := range []struct {
		in            string
		maj, min, pat int
	}{
		{"6.18.34+rpt-rpi-v8", 6, 18, 34},
		{"6.6.51-v8-16k+", 6, 6, 51},
		{"6.1.0-rpi7-rpi-v8", 6, 1, 0},
	} {
		k := parseKernel(tc.in)
		if k.Major != tc.maj || k.Minor != tc.min || k.Patch != tc.pat {
			t.Errorf("parseKernel(%q) = %d.%d.%d, want %d.%d.%d",
				tc.in, k.Major, k.Minor, k.Patch, tc.maj, tc.min, tc.pat)
		}
	}
}
